### ISSUE TITLE
Having Trouble Getting It To Work

### ISSUE THREAD

**Issue by enenoir** [developers192/DetailedLoLRPC#1]
I could just be dumb but I can't get it to work :( 

I followed the 4 steps and it just doesn't work... The presence just won't show at all, or it does show but it will just be the default league icon and how long I've been playing for. No champ picture, No lobby info, No nothing... 

Also, I got two different error windows when I was trying to fix it by trying to uninstall and install it again. 

The first one was "no folder found" or smth, but that never showed again after I installed it with the Client open

The last one was "Unhandled exception in script" that I personally don't know what it means and it only showed the first time ran the setup.exe

Now it will open and all with no error window but it doesn't work :(

**Comment by developers192** [comment]
Hey there,
It would help a ton if you could screenshot the error messages. For now, my only guess is that it could be your antivirus doing things.
Also can you check inside the folder in which you put the files in? After running setup.exe there should be: DetailedLoLRPC.exe, setup.exe, RiotGamesPath.txt, StartLoL.exe and the League of Legends shortcut.

**Comment by enenoir** [comment]
I do have all of these inside the folder I extracted the latest Release!

and... since I can't send images in here... ill just copy and paste it

```

Unhandled exception in script


❌ Failed to execute script 'DetailedLoLRPC' due to unhandled exception: 0, message='0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/en_us/v1/discord_strings.json')

Traceback (most recent call last):
  File "DetailedLoLRPC.py", line 118, in <module>
  File "lcu_driver\connector.py", line 70, in start
  File "lcu_driver\connector.py", line 64, in wrapper
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "lcu_driver\connection.py", line 76, in init
  File "lcu_driver\events\managers.py", line 30, in run_event
  File "DetailedLoLRPC.py", line 30, in connect
  File "aiohttp\client_reqrep.py", line 1104, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/en_us/v1/discord_strings.json')
```

Also if it is my antivirus.. is there anything I can do? I just have the default Windows Security one

**Comment by developers192** [comment]
Got it, its not your antivirus but a dumb bug. My bad 🥹
I'll fix it asap, currently enjoying my meal rn. Also if you encounter any other messages please drop them here. Thank you!

**Comment by enenoir** [comment]
ohhh there's no rush!! and ofc! I'll make sure to do that!

Thank you for the quick responses and Enjoy your meal!! 😊

**Comment by developers192** [comment]
As this only happens for the NA region, I can't test this fix out. Here's the file:
https://cdn.discordapp.com/attachments/1131476067757068298/1131476114720690186/DetailedLoLRPC_v1.1.zip
Can you test this out before I release it? Thanks

**Comment by enenoir** [comment]
It worked perfectly now!! 😊 I looks really nice too!! Thank you so much!! ♡

**Comment by developers192** [comment]
Np. Thank you for reporting the bug ♡
