### ISSUE TITLE
The Future of this Project

### ISSUE THREAD

**Issue by BreakingTV** [developers192/DetailedLoLRPC#10]
Will the new Anti-cheat changes make this program useless?
It tinkers with the league files and I think the anti-cheat would not like it that much...

**Comment by developers192** [comment]
It probably would still work. The only file which DLRPC touches is meant to be "editable" by the end user and it does not inject into the game like the custom skins programs do. However, things may change, I don't know. When the anticheat update comes out I'll do some testing and make announcements or updates if necessary.

**Comment by DereC4** [comment]
does it only perform read operations?

**Comment by BreakingTV** [comment]
As the Readme states:
_DetailedLoLRPC only uses the API provided by the Client itself. Although it does tamper with the plugin-manifest.json file_

**Comment by developers192** [comment]
Yes it does make edits to the file, you can read the reddit post about it at the end of the README. When the update drops, I will do some testing, you can stop using the rpc until I make an update about it. Even if you do get banned, it probably can be appealed easily as the rpc does not provide unfair advantages to the user.

**Comment by developers192** [comment]
As expected, it worked fine with Vanguard on PBE. This means 99% that it will work when Vanguard drops on the live server, unless they change something... We're good for now.
