### ISSUE TITLE
Question for you

### ISSUE THREAD

**Issue by Snowballneko** [developers192/DetailedLoLRPC#13]
I was wondering if there would be a way to completely disable Discord rich presence? I've been trying to figure something out but I do not think I am smart enough. Thank you for any help if you are able to.

**Comment by developers192** [comment]
What do you mean by that though... You can completely disable Rich Presence for all games by going in the settings -> Activity privacy and turn off display current activity...

**Comment by Snowballneko** [comment]
I mean, remove rich presence just for Leauge. I want all other activity and other rich presents to show, I just don't want League.

**Comment by developers192** [comment]
You can look into the disabler.py file to see the code there, but it does tamper with League's files so I don't know if it will work or not when Vanguard gets implemented.

**Comment by Snowballneko** [comment]
I am dumb, so I have no idea how I could make the disabler work standalone. 😔

**Comment by developers192** [comment]
Sorry for the very late reply, according to Discord, you can disable rich presence detection for specific games following this [guide](https://support.discord.com/hc/en-us/articles/7931156448919-Activity-Status-Recent-Activity#Game-Detection:~:text=are%20also%20on.-,Game%20Detection,-You%20can%20enable)
