### ISSUE TITLE
League status text in RPC

### ISSUE THREAD

**Issue by MVukanichh** [developers192/DetailedLoLRPC#14]
Is it possible to have League status text shown in the Discord RPC, while out of lobby?

**Comment by DereC4** [comment]
im getting crashes after using this; is that normal?

**Comment by developers192** [comment]
> Is it possible to have League status text shown in the Discord RPC, while out of lobby?

Right-click the tray icon, then you can select the Idling status that you want.

**Comment by developers192** [comment]
> im getting crashes after using this; is that normal?

Can you post the crash logs here? Thanks
