### ISSUE TITLE
it says it can't find discord but i have it on :(

### ISSUE THREAD

**Issue by persephoneirl** [developers192/DetailedLoLRPC#15]
it gives me an error saying it can't find discord on the machine but i have it on, maybe perhaps it's cause i use vencord along with it? i used to have windows 10 with vencord as well and it worked fine but i switched to windows 11 after my pc reset

**Comment by developers192** [comment]
You should have discord/vencord **already running** when opening DetailedLoLRPC.exe

**Comment by persephoneirl** [comment]
i do already have it on, my discord opens automatically the moment i turn
on my pc

*Bela*

**Comment by developers192** [comment]
Strange. I'll look into it. Can you screenshot the error?

**Comment by persephoneirl** [comment]
ofc! i will screenshot it when i get back on pc in a few hours, if it gives
me the error again! if it fixed itself by then i’ll also let you know :)

*Bela*

**Comment by persephoneirl** [comment]
hello!! i tried it just now and it gave me the error again, as u can see i have discord open in the bg as i took the ss
![image](https://github.com/developers192/DetailedLoLRPC/assets/169947496/d92573cd-c37d-47d3-a287-202d1d85a2d3)

**Comment by developers192** [comment]
this is super strange lol, i'll take a look when i have time

**Comment by persephoneirl** [comment]
hi! i tried it again now to see if it was just a tiny error but nope :( i can send u the files
[sessionlog.json](https://github.com/user-attachments/files/15777108/sessionlog.json)

**Comment by persephoneirl** [comment]
as seen on my session log, there's nothing :(

**Comment by developers192** [comment]
Apparently according to this [issue](https://github.com/qwertyquerty/pypresence/issues/240), the library does not support Vencord. I will try to find a workaround for this. In the meantime, if you still want to use DLRPC you'd probably have to uninstall Vencord unfortunately.

**Comment by developers192** [comment]
Actually I just installed Vencord myself and the rich presence is still working as intended. Did you install Vencord to another discord version like Canary or Beta?

**Comment by persephoneirl** [comment]
no it’s on main discord :c

*Bela*

**Comment by developers192** [comment]
Try disabling RPC-related plugins like CustomRPC and NoRPC

**Comment by persephoneirl** [comment]
i will real quick and tel you

*Bela*

**Comment by persephoneirl** [comment]
it seems to have worked to remove those plugins, tysm!! 💗

*Bela*

**Comment by developers192** [comment]
No problem. Glad i helped!
