### ISSUE TITLE
broken splash art link

### ISSUE THREAD

**Issue by DereC4** [developers192/DetailedLoLRPC#16]
![image](https://github.com/developers192/DetailedLoLRPC/assets/53978637/ec6681f9-55fd-4400-ab7a-65dc722d17c2)

Not sure why this is happening

**Comment by developers192** [comment]
I am aware of this. A fix coming in 1 or 2 days

**Comment by developers192** [comment]
Fixed in the latest release. Thank for reporting!

**Comment by DereC4** [comment]
w
