### ISSUE TITLE
[Feature Request] Add swarm support

### ISSUE THREAD

**Issue by BreakingTV** [developers192/DetailedLoLRPC#18]
Hello again!
As the title already says, I would love to see the swarm mode supported in this project!
To get information of wich stage it is on or what map/champ is played. There could be so much potential!

Sadly I cant code in python very good, if I could I would already made a pull request :(
I would love to see this gamemode supported with the full potential!

(Please mind that english is sadly not my first language :/)

**Comment by developers192** [comment]
Surely. Unfortunately I'm not at home right now so maybe I'll update it in the next few days. I haven't even tried the mode myself

**Comment by BreakingTV** [comment]
Oh okay, cant wait!

**Comment by developers192** [comment]
Added in the latest release. Unfortunately I can only do current champion because the API is a real mess and they did a bunch of workarounds for this new mode to work. Anyways thanks for requesting this!
