### ISSUE TITLE
wrong champ displays when playing on the new ME server

### ISSUE THREAD

**Issue by pauv-re** [developers192/DetailedLoLRPC#19]
Basically what the title says - when playing in the ME server, whichever champ shows up on the toplaner slot gets shown on the status instead of the champ you're actually using. I thought it was an issue on my side at first, but after playing and seeing how the status worked normally on both the EUW and EUNE servers I can safely say that the bug is tied to me being on ME. I'm not sure if the issue persists on the other modes since I've only seen it happen through Quickplay, but it's probably worth looking into if it's not too bothersome! :,)

**Comment by developers192** [comment]
After you finish a game, can you right-click the tray icon, press "Report bug," and upload the sessionlog.json file in the opened window here? Also, it would help if you try a draft pick or ARAM to see if the issue persists. I might create a ME account to check it out.

**Comment by developers192** [comment]
I think I know why. The client uses the old display name internally instead of the Riot ID to list players. Since ME is a new server, no one has that old display name, so everyone's display name is set to blank. DLRPC matched your display name, which is blank, to the first player's in the list, which is also blank. I will try to fix this soon, it's midnight here atm

**Comment by pauv-re** [comment]
hi there!! sorry for the late reply, i just saw this :(

i'll try to submit the .json file tomorrow if you still need it since it's really late for me rn. i'll try to see if the problem persists in ARAM games too (there's no draft pick mode in ME)

ty so much for ur response tho!!

**Comment by pauv-re** [comment]
[sessionlog.json](https://github.com/user-attachments/files/16392534/sessionlog.json)

here's the sessionlog for one Quickplay game!

i queued up for an ARAM game too and the same issue applies so i'm assuming the same for the rest of the modes (not sure about Swarm though)

**Comment by developers192** [comment]
I just put together a quick fix. Check out the latest release [v3.2.0](https://github.com/developers192/DetailedLoLRPC/releases/tag/v3.2.0). Let me know if it works for you!

**Comment by pauv-re** [comment]
hi again!! so sorry for the late response, i've only been able to play today but the good thing is that everything displays correctly now :)

thank you so much!!

**Comment by developers192** [comment]
No problem. Thanks for reporting.!
