### ISSUE TITLE
Stuck in Champion Select

### ISSUE THREAD

**Issue by khang152xx** [developers192/DetailedLoLRPC#2]
I'm STUCK

**Comment by developers192** [comment]
Can you provide more info? Screenshots? Error messages?

**Comment by khang152xx** [comment]
> Can you provide more info? Screenshots? Error messages?

![image](https://github.com/developers192/DetailedLoLRPC/assets/146123413/0a72c35b-8c91-4ad2-8844-06f737f63c61)

**Comment by khang152xx** [comment]
> Can you provide more info? Screenshots? Error messages?

When I finish selecting my champion and enter the match, Discord only indicates that I am selecting a champion but does not display the name of the champion I have chosen or am currently playing

**Comment by khang152xx** [comment]
> Can you provide more info? Screenshots? Error messages?

And it continues like this until the end of the match, and everything returns to normal. In summary, it only shows up outside the client, but during the match, there's nothing.

**Comment by developers192** [comment]
Okay, can you check if you are on the latest version? Which champion were you playing and which skin have you used? Can you send me your current preferences in they tray menu?

**Comment by developers192** [comment]
Okay, I'll look into it when i have time. Thanks for reporting.

**Comment by khang152xx** [comment]
> Okay, I'll look into it when i have time. Thanks for reporting.


Thank you for your response; I really like this RPC. Please fix the issue for me quickly.

**Comment by developers192** [comment]
Okay, I just made this beta version and I want you to try if it helps: [Download](https://cdn.discordapp.com/attachments/897687565442883585/1157624620623605770/DetailedLoLRPC.exe?ex=65194971&is=6517f7f1&hm=b4d5e381935bde1a7998be76592dece096347838d3a36bb809e5156edbf74d08&)
If it doesn't, I want you to right-click the tray icon and press "Report bug", then upload the "sessionlog.json" file in the opened Explorer window here.

**Comment by khang152xx** [comment]
[{"internalName": "KhangRu\u1ed3i", "summonerId": 3112226557486656, "locale": "vi_vn"}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "ChampSelect", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 7, "spell1Id": 4, "spell2Id": 12, "summonerInternalName": "Khang Ru\u1ed3i"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "ChampSelect", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 7, "spell1Id": 4, "spell2Id": 12, "summonerInternalName": "Khang Ru\u1ed3i"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "GameStart", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 7, "spell1Id": 4, "spell2Id": 12, "summonerInternalName": "Khang Ru\u1ed3i"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "WaitingForStats", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 7, "spell1Id": 4, "spell2Id": 12, "summonerInternalName": "Khang Ru\u1ed3i"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "WaitingForStats", "lobbyMem": 4}]

It still doesn't work, it's still stuck at the champion selection

**Comment by developers192** [comment]
Got it, it's a bug related to special characters in your name. I'll try to fix this asap.

**Comment by khang152xx** [comment]
I don't think so, I used a different account with no special characters in the name. But it still happened. Is this issue only happening with the Vietnamese language ?

**Comment by khang152xx** [comment]
[{"internalName": "CuSangKenny", "summonerId": 3112235202536736, "locale": "vi_vn"}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "ChampSelect", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": "Cu Sang Kenny"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "ChampSelect", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": "Cu Sang Kenny"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "GameStart", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": "Cu Sang Kenny"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "WaitingForStats", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": [{"championId": 266, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": "Cu Sang Kenny"}]}, "queueData": {"type": "PRACTICE_GAME", "category": "Custom", "description": "Ph\u00f2ng T\u1eadp", "gameMode": "PRACTICETOOL", "mapId": 11, "maximumParticipantListSize": 1}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "WaitingForStats", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "", "category": "None", "description": "", "gameMode": "", "mapId": 0, "maximumParticipantListSize": 0}, "mapData": {"name": "", "mapStringId": ""}, "phase": "None", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Matchmaking", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Matchmaking", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Lobby", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Matchmaking", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Matchmaking", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "Matchmaking", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "ReadyCheck", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": []}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "ChampSelect", "lobbyMem": 1}, {"gameData": {"playerChampionSelections": [{"championId": 523, "selectedSkinIndex": 0, "spell1Id": 1, "spell2Id": 4, "summonerInternalName": "IAF Payz"}, {"championId": 412, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": "t\u1eaft\u0111\u00e8nn\u0111ii"}, {"championId": 105, "selectedSkinIndex": 0, "spell1Id": 14, "spell2Id": 4, "summonerInternalName": "KN Exim"}, {"championId": 233, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 11, "summonerInternalName": "\u00ba\u00d1g\u1ecdc\u00ba "}, {"championId": 41, "selectedSkinIndex": 0, "spell1Id": 12, "spell2Id": 4, "summonerInternalName": "C\u00e0ng C\u00fam Ram Me"}, {"championId": 101, "selectedSkinIndex": 1, "spell1Id": 4, "spell2Id": 3, "summonerInternalName": "zZzNangzZz"}, {"championId": 59, "selectedSkinIndex": 9, "spell1Id": 11, "spell2Id": 4, "summonerInternalName": "Bad Dragons"}, {"championId": 14, "selectedSkinIndex": 3, "spell1Id": 6, "spell2Id": 12, "summonerInternalName": "7CO"}, {"championId": 245, "selectedSkinIndex": 19, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": " ba que gaming"}, {"championId": 29, "selectedSkinIndex": 8, "spell1Id": 4, "spell2Id": 6, "summonerInternalName": "Cu Sang Kenny"}]}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "GameStart", "lobbyMem": 4}, {"gameData": {"playerChampionSelections": [{"championId": 523, "selectedSkinIndex": 0, "spell1Id": 1, "spell2Id": 4, "summonerInternalName": "IAF Payz"}, {"championId": 412, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": "t\u1eaft\u0111\u00e8nn\u0111ii"}, {"championId": 105, "selectedSkinIndex": 0, "spell1Id": 14, "spell2Id": 4, "summonerInternalName": "KN Exim"}, {"championId": 233, "selectedSkinIndex": 0, "spell1Id": 4, "spell2Id": 11, "summonerInternalName": "\u00ba\u00d1g\u1ecdc\u00ba "}, {"championId": 41, "selectedSkinIndex": 0, "spell1Id": 12, "spell2Id": 4, "summonerInternalName": "C\u00e0ng C\u00fam Ram Me"}, {"championId": 101, "selectedSkinIndex": 1, "spell1Id": 4, "spell2Id": 3, "summonerInternalName": "zZzNangzZz"}, {"championId": 59, "selectedSkinIndex": 9, "spell1Id": 11, "spell2Id": 4, "summonerInternalName": "Bad Dragons"}, {"championId": 14, "selectedSkinIndex": 3, "spell1Id": 6, "spell2Id": 12, "summonerInternalName": "7CO"}, {"championId": 245, "selectedSkinIndex": 19, "spell1Id": 4, "spell2Id": 14, "summonerInternalName": " ba que gaming"}, {"championId": 29, "selectedSkinIndex": 8, "spell1Id": 4, "spell2Id": 6, "summonerInternalName": "Cu Sang Kenny"}]}, "queueData": {"type": "RANKED_SOLO_5x5", "category": "PvP", "description": "X\u1ebfp H\u1ea1ng \u0110\u01a1n/\u0110\u00f4i", "gameMode": "CLASSIC", "mapId": 11, "maximumParticipantListSize": 2}, "mapData": {"name": "Summoner's Rift", "mapStringId": "SR"}, "phase": "ChampSelect", "lobbyMem": 4}]

**Comment by developers192** [comment]
No. I meant names with spaces. Try this, the bug should be fixed: [Download](https://cdn.discordapp.com/attachments/897687565442883585/1158137326908756019/DetailedLoLRPC.exe?ex=651b26ef&is=6519d56f&hm=21e79df854310f6794c372bcfe9655c6189f177091c9f35550a76a86efbc6cc7&). Just skip the update popup. Let me know if it works.

**Comment by khang152xx** [comment]
Thank u very much, it's working perfect now!

**Comment by developers192** [comment]
No problem. Thanks for using DetailedLoLRPC. I will release the actual version later, which will remove the update popup.
