### ISSUE TITLE
Unhandled Exception in Script?

### ISSUE THREAD

**Issue by Fenlynndafox** [developers192/DetailedLoLRPC#4]
Hi! Everytime I try to use this plugin it gives me this popup. Any clues on how to fix it?

![image (11)](https://github.com/developers192/DetailedLoLRPC/assets/149350502/6ddde7b2-7bcd-4ab4-a9d1-82a790b626f7)

**Comment by developers192** [comment]
So you just open the EXE and this popped up? Or it did only when you joined a match?

**Comment by Fenlynndafox** [comment]
It only pops up after I close League. I open it, run as admin, and it
doesn’t work when I get into a game.

**Comment by developers192** [comment]
Probably a bug on my side, I'll look into it. Have you tried not running it as admin? Can you right click the tray icon, press "Report bug" and then upload the sessionlog.json file here?

**Comment by Fenlynndafox** [comment]
[sessionlog.json](https://github.com/developers192/DetailedLoLRPC/files/13221126/sessionlog.json)

**Comment by developers192** [comment]
Nice. Can you cause that error to pop up again, then scroll down so I can see the last lines?

**Comment by Fenlynndafox** [comment]
That's all that comes up, here's the most recent one. 
[sessionlog.json](https://github.com/developers192/DetailedLoLRPC/files/13223488/sessionlog.json)

**Comment by developers192** [comment]
I just made this beta version that should have fixed the bug. Please test this out before I release it and let me know if it works: [Download](https://cdn.discordapp.com/attachments/897687565442883585/1169289020291940373/DetailedLoLRPC.exe?ex=6554dc42&is=65426742&hm=b25b04a03c36a7fec5bb57e3ebea42ddaf13d7a78421e33d70e60189dff013ac&)

**Comment by developers192** [comment]
Np. Thank for reporting this!
