### ISSUE TITLE
How do i change the directory?

### ISSUE THREAD

**Issue by RyuHZz** [developers192/DetailedLoLRPC#5]

**Comment by developers192** [comment]
So you moved your Riot Games folder to another directory right? Just right click the tray icon, press "Reset preferences", "Exit" and reopen it.

**Comment by RyuHZz** [comment]
![image_2023-11-01_010646414](https://github.com/developers192/DetailedLoLRPC/assets/149541357/ed9b315d-7d05-462b-ba24-cc92e5730e19)
now i get this and it doesnt work, it happens when i close the client

**Comment by developers192** [comment]
Okay, please right click the tray icon, press Report bug and upload the sessionlog.json file here.

**Comment by developers192** [comment]
This has been fixed in the latest release. Please update and thanks for reporting!
