### ISSUE TITLE
Arena RPC not disappearing after exiting early

### ISSUE THREAD

**Issue by BreakingTV** [developers192/DetailedLoLRPC#8]
The Title says almost everything.
When you lose Arena early, and exit to the launcher the RPC will still show that you play, until the entire game is stopped.
This happend already 2 times, maybe it was an error at my side. Just wanted to mention it

**Comment by developers192** [comment]
Sure, I'll take a look

**Comment by BreakingTV** [comment]
Just an Update, same is happening with TFT.
Placed 2nd, so the game stopped. Still the RPC shows. I think its becouse of the gamemodes you can Quit early, but not sure.

**Comment by developers192** [comment]
Got it. Unfortunately I'm still busy with important school stuffs so I don't have time to look at this anytime soon, probably about 1 or 2 weeks maximum. Thanks for keeping me updated with this tho!

**Comment by developers192** [comment]
Hi there, I'm back. When this happens again, can you right-click the tray icon, press Report bug and upload the sessionlog.json file here please. Thanks

**Comment by BreakingTV** [comment]
Heyy, happy new years!
The Problem is... I am no longer on Windows and I play league on Linux... so I cant use the program right now.

I can reinstall Windows and try it out there, could take some time tho...

**Comment by developers192** [comment]
That's unfortunate xD. I have a spare linux PC so I might try to implement linux support sometime later... Thanks for replying and
Happy new year!!
