### ISSUE TITLE
Windows complaining about it beeing a bank trojan

### ISSUE THREAD

**Issue by BreakingTV** [developers192/DetailedLoLRPC#9]
Just wanted to mention it, as it's annoying
But why a... bank trojan? I would understand why it think it could be some other malware but not a bank trojan...?

**Comment by developers192** [comment]
So python-exe files like this usually triggers false-positives. On the other hand, you can easilly decompile it to literal source code and compare it with the code on GitHub. So yeah, if it's really a virus, there should be a reddit post about it already...You can add it to the exclusions to prevent it from popping up again tho

**Comment by BreakingTV** [comment]
Okay, 
firstly thanks for the advice to add it to the exclusions, dont use much Windows expect from gaming
secondly, I meant to ask why its specificly a bank trojan? I thought maybe there is some reason behind it...

Still thanks tho!

**Comment by developers192** [comment]
I don't know xD. I my Windows Defender personally don't detect it as a threat at all. Maybe you can send me the screenshot of it warning u

**Comment by BreakingTV** [comment]
I would have... but I downloaded it now and no error...
I dont know what Windows changed his mind, but I guess somthing did...

In my Browser history I can see that the trojan Code was: Win32/Phonzy.B!ml
Maybe this helps a bit more...

If I get the error again, I will post a screenshot... until then I think this is done XD

**Comment by developers192** [comment]
Good luck! Rest assured that there won't be any trojan in any of my executables ever
